stages:
  - "Install"
  - "Tests"

###########################################
#   ____  ___  _        _    _   _  ____  #
#  / ___|/ _ \| |      / \  | \ | |/ ___| #
# | |  _| | | | |     / _ \ |  \| | |  _  #
# | |_| | |_| | |___ / ___ \| |\  | |_| | #
#  \____|\___/|_____/_/   \_\_| \_|\____| #
#                                         #
###########################################

.template-GoLang:
  image: golang:1.13-alpine
  before_script:
    - cd ./go
  only:
    - go

Tests-GoLang:
  extends: .template-GoLang
  stage: "Tests"
  script:
    - go test ./tests/ -v

#############################
#       _   ___     ___     #
#      | | / \ \   / / \    #
#   _  | |/ _ \ \ / / _ \   #
#  | |_| / ___ \ V / ___ \  #
#   \___/_/   \_\_/_/   \_\ #
#                           #
#############################

.template-Java:
  image: maven:3.6-slim
  before_script:
    - cd ./java
  only:
    - java

Tests-Java:
  extends: .template-Java
  stage: "Tests"
  script:
    - mvn test

#####################################
#   _  _____ _____ _     ___ _   _  #
#  | |/ / _ \_   _| |   |_ _| \ | | #
#  | ' / | | || | | |    | ||  \| | #
#  | . \ |_| || | | |___ | || |\  | #
#  |_|\_\___/ |_| |_____|___|_| \_| #
#                                   #
#####################################

.template-Kotlin:
  image: gradle:6.0-jdk13
  before_script:
    - cd ./kotlin
  only:
    - kotlin

Tests-Kotlin:
  extends: .template-Kotlin
  stage: "Tests"
  script:
    - gradle test

########################################
#  ______   _______ _   _  ___  _   _  #
# |  _ \ \ / /_   _| | | |/ _ \| \ | | #
# | |_) \ V /  | | | |_| | | | |  \| | #
# |  __/ | |   | | |  _  | |_| | |\  | #
# |_|    |_|   |_| |_| |_|\___/|_| \_| #
#                                      #
########################################

.template-Python:
  image: python:3.7-slim
  before_script:
    - cd ./python
  only:
    - python

Tests-Python:
  extends: .template-Python
  stage: "Tests"
  script:
    - python -m unittest discover -s tests -p *_test.py

########################
#   ____  _   _ ____   #
#  |  _ \| | | |  _ \  #
#  | |_) | |_| | |_) | #
#  |  __/|  _  |  __/  #
#  |_|   |_| |_|_|     #
#                      #
########################

.template-PHP:
  image: composer:1.9
  before_script:
    - cd ./php
  only:
    - php

Install-PHP:
  extends: .template-PHP
  stage: "Install"
  script:
    - composer install
    - composer dump-autoload -o
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
  artifacts:
    untracked: true
    expire_in: 1 hour

Tests-PHP:
  extends: .template-PHP
  stage: "Tests"
  script:
    - composer test

########################################
#   ____   ____    _    _        _     #
#  / ___| / ___|  / \  | |      / \    #
#  \___ \| |     / _ \ | |     / _ \   #
#   ___) | |___ / ___ \| |___ / ___ \  #
#  |____/ \____/_/   \_\_____/_/   \_\ #
#                                      #
########################################

.template-Scala:
  image: hseeberger/scala-sbt:8u222_1.3.3_2.13.1
  before_script:
    - cd ./scala
  only:
    - scala

Tests-Scala:
  extends: .template-Scala
  stage: "Tests"
  script:
    - sbt test

###############################################################
#   _______   ______  _____ ____   ____ ____  ___ ____ _____  #
#  |_   _\ \ / /  _ \| ____/ ___| / ___|  _ \|_ _|  _ \_   _| #
#    | |  \ V /| |_) |  _| \___ \| |   | |_) || || |_) || |   #
#    | |   | | |  __/| |___ ___) | |___|  _ < | ||  __/ | |   #
#    |_|   |_| |_|   |_____|____/ \____|_| \_\___|_|    |_|   #
#                                                             #
###############################################################

.template-TypeScript:
  image: node:latest
  before_script:
    - cd ./typescript
  only:
    - typescript

Install-TypeScript:
  extends: .template-TypeScript
  stage: "Install"
  script:
    - yarn
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  artifacts:
    untracked: true
    expire_in: 1 hour

Tests-TypeScript:
  extends: .template-TypeScript
  stage: "Tests"
  script:
    - yarn test
